# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Météo Paris' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Météo Paris
	pod 'SwiftyJSON'

  target 'Météo ParisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Météo ParisUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
