# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Meteo Paris' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Météo Paris
	pod 'SwiftyJSON'
    pod 'SwiftyTimer'
    pod 'RainyRefreshControl'
    
  target 'Meteo ParisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Meteo ParisUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
